'use client'

import React from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Dialog } from '@/shared/ui/dialog'
import { SpinnerIcon } from '@/shared/ui/SpinnerIcon'
import { ErrorBanner } from '@/shared/ui/ErrorBanner'
import { showToast } from '@/shared/ui/toast'
import { cn } from '@/shared/lib/utils'
import { useUpdateSegment } from '../mutations'
import type { SegmentResponse } from '../api'

const schema = z.object({
  name: z.string().min(1, 'Name is required').max(255, 'Name must be 255 characters or fewer'),
  definition_json: z
    .string()
    .refine((v) => {
      try { JSON.parse(v); return true } catch { return false }
    }, 'Must be valid JSON'),
  estimated_size: z
    .string()
    .transform((v) => (v === '' ? undefined : parseInt(v, 10)))
    .pipe(z.number().int().min(0, 'Must be 0 or greater').optional()),
})

type FormValues = z.input<typeof schema>
type FormOutput = z.output<typeof schema>

interface SegmentEditModalProps {
  segment: SegmentResponse
  showId: string
  open: boolean
  onClose: () => void
}

export function SegmentEditModal({ segment, showId, open, onClose }: SegmentEditModalProps) {
  const updateMutation = useUpdateSegment(showId)

  const defaultValues = {
    name: segment.name,
    definition_json: JSON.stringify(segment.definition_json, null, 2),
    estimated_size: segment.estimated_size != null ? String(segment.estimated_size) : '',
  }

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<FormValues, unknown, FormOutput>({
    resolver: zodResolver(schema),
    defaultValues,
  })

  function handleClose() {
    reset(defaultValues)
    onClose()
  }

  function onSubmit(values: FormOutput) {
    updateMutation.mutate(
      {
        segmentId: segment.segment_id,
        name: values.name,
        definitionJson: JSON.parse(values.definition_json) as Record<string, unknown>,
        estimatedSize: values.estimated_size,
      },
      {
        onSuccess: () => {
          showToast('Segment saved', 'success')
          onClose()
        },
      }
    )
  }

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      title="Edit segment"
      description="Edit the name, definition, and estimated size of this segment."
    >
      <form onSubmit={handleSubmit(onSubmit)} noValidate>
        {updateMutation.isError && (
          <div className="mb-4">
            <ErrorBanner message="Failed to save segment. Please try again." />
          </div>
        )}

        {/* Name field */}
        <div className="space-y-1">
          <label htmlFor="segment-name" className="block text-xs font-medium text-text-muted">
            Name
          </label>
          <input
            id="segment-name"
            type="text"
            {...register('name')}
            disabled={updateMutation.isPending}
            className={cn(
              'w-full rounded-md border bg-bg px-3 py-2 text-sm text-text placeholder:text-text-muted',
              'focus:border-primary focus:outline-none disabled:opacity-50',
              errors.name ? 'border-red-500' : 'border-border'
            )}
          />
          {errors.name && (
            <p role="alert" className="text-xs text-red-600">
              {errors.name.message}
            </p>
          )}
          {/* Original agent value */}
          <p className="text-xs text-text-muted">
            Original: <span className="italic">{segment.name}</span>
            {segment.created_by && (
              <> &middot; Generated by {segment.created_by}</>
            )}
          </p>
        </div>

        {/* Definition JSON field */}
        <div className="mt-4 space-y-1">
          <label htmlFor="segment-definition-json" className="block text-xs font-medium text-text-muted">
            Definition JSON
          </label>
          <textarea
            id="segment-definition-json"
            {...register('definition_json')}
            disabled={updateMutation.isPending}
            rows={6}
            className={cn(
              'w-full rounded-md border bg-bg px-3 py-2 font-mono text-xs text-text placeholder:text-text-muted',
              'focus:border-primary focus:outline-none disabled:opacity-50',
              errors.definition_json ? 'border-red-500' : 'border-border'
            )}
          />
          {errors.definition_json && (
            <p role="alert" className="text-xs text-red-600">
              {errors.definition_json.message}
            </p>
          )}
        </div>

        {/* Estimated size field */}
        <div className="mt-4 space-y-1">
          <label htmlFor="segment-estimated-size" className="block text-xs font-medium text-text-muted">
            Estimated size <span className="font-normal">(optional)</span>
          </label>
          <input
            id="segment-estimated-size"
            type="number"
            min={0}
            {...register('estimated_size')}
            disabled={updateMutation.isPending}
            className={cn(
              'w-full rounded-md border bg-bg px-3 py-2 text-sm text-text placeholder:text-text-muted',
              'focus:border-primary focus:outline-none disabled:opacity-50',
              errors.estimated_size ? 'border-red-500' : 'border-border'
            )}
          />
          {errors.estimated_size && (
            <p role="alert" className="text-xs text-red-600">
              {errors.estimated_size.message as string}
            </p>
          )}
          {segment.estimated_size != null && (
            <p className="text-xs text-text-muted">
              Original: <span className="italic">{segment.estimated_size.toLocaleString()}</span>
            </p>
          )}
        </div>

        <div className="mt-6 flex justify-end gap-3">
          <button
            type="button"
            onClick={handleClose}
            disabled={updateMutation.isPending}
            className="rounded-md px-4 py-2 text-sm font-medium text-text-muted hover:bg-bg disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={updateMutation.isPending}
            className={cn(
              'inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-sm font-medium text-white',
              'hover:opacity-90 disabled:opacity-50'
            )}
          >
            {updateMutation.isPending && <SpinnerIcon className="h-4 w-4" />}
            {updateMutation.isPending ? 'Saving\u2026' : 'Save'}
          </button>
        </div>
      </form>
    </Dialog>
  )
}
