import React from 'react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { SegmentEditModal } from './SegmentEditModal'
import type { SegmentResponse } from '../api'

const mockUpdate = vi.fn()

vi.mock('../mutations', () => ({
  useUpdateSegment: () => ({
    mutate: mockUpdate,
    isPending: false,
  }),
  useApproveSegment: () => ({
    mutate: vi.fn(),
    isPending: false,
  }),
  useRejectSegment: () => ({
    mutate: vi.fn(),
    isPending: false,
  }),
  useUndoSegmentReview: () => ({
    mutate: vi.fn(),
    isPending: false,
  }),
}))

const SHOW_ID = 'show-1'

const segment: SegmentResponse = {
  segment_id: 'seg-1',
  show_id: SHOW_ID,
  cycle_id: 'cycle-1',
  name: 'Gen Pop',
  definition_json: { age_range: '18-35' },
  estimated_size: 5000,
  created_by: 'agent',
  review_status: 'pending',
  reviewed_at: null,
  reviewed_by: null,
}

function renderModal(overrides: { open?: boolean; onClose?: () => void } = {}) {
  const onClose = overrides.onClose ?? vi.fn()
  return {
    ...render(
      <SegmentEditModal
        segment={segment}
        showId={SHOW_ID}
        open={overrides.open ?? true}
        onClose={onClose}
      />
    ),
    onClose,
  }
}

describe('SegmentEditModal', () => {
  beforeEach(() => {
    mockUpdate.mockReset()
  })

  describe('rendering', () => {
    it('renders dialog when open', () => {
      renderModal()
      expect(screen.getByRole('dialog', { name: /edit segment/i })).toBeInTheDocument()
    })

    it('does not render when closed', () => {
      renderModal({ open: false })
      expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    })

    it('pre-fills name field with current segment name', () => {
      renderModal()
      expect(screen.getByLabelText(/name/i)).toHaveValue('Gen Pop')
    })

    it('pre-fills estimated size field', () => {
      renderModal()
      expect(screen.getByLabelText(/estimated size/i)).toHaveValue(5000)
    })

    it('shows original agent values as read-only reference', () => {
      renderModal()
      const originals = screen.getAllByText(/original/i)
      expect(originals.length).toBeGreaterThanOrEqual(1)
      expect(screen.getByText(/gen pop/i, { selector: 'span' })).toBeInTheDocument()
    })

    it('shows generated-by attribution', () => {
      renderModal()
      expect(screen.getByText(/generated by agent/i)).toBeInTheDocument()
    })

    it('renders Save and Cancel buttons', () => {
      renderModal()
      expect(screen.getByRole('button', { name: /^save$/i })).toBeInTheDocument()
      expect(screen.getByRole('button', { name: /^cancel$/i })).toBeInTheDocument()
    })
  })

  describe('form validation', () => {
    it('shows error when name is empty on submit', async () => {
      const user = userEvent.setup()
      renderModal()
      await user.clear(screen.getByLabelText(/name/i))
      await user.click(screen.getByRole('button', { name: /^save$/i }))
      expect(await screen.findByRole('alert')).toHaveTextContent(/name is required/i)
      expect(mockUpdate).not.toHaveBeenCalled()
    })

    it('shows error when name exceeds 255 characters', async () => {
      const user = userEvent.setup()
      renderModal()
      await user.clear(screen.getByLabelText(/name/i))
      await user.type(screen.getByLabelText(/name/i), 'x'.repeat(256))
      await user.click(screen.getByRole('button', { name: /^save$/i }))
      expect(await screen.findByRole('alert')).toHaveTextContent(/255 characters/i)
      expect(mockUpdate).not.toHaveBeenCalled()
    })

    it('shows error when estimated size is negative', async () => {
      const user = userEvent.setup()
      renderModal()
      await user.clear(screen.getByLabelText(/estimated size/i))
      await user.type(screen.getByLabelText(/estimated size/i), '-1')
      await user.click(screen.getByRole('button', { name: /^save$/i }))
      expect(await screen.findByRole('alert')).toHaveTextContent(/0 or greater/i)
      expect(mockUpdate).not.toHaveBeenCalled()
    })
  })

  describe('submission', () => {
    it('calls updateMutation with name and estimatedSize on valid submit', async () => {
      const user = userEvent.setup()
      renderModal()
      await user.clear(screen.getByLabelText(/name/i))
      await user.type(screen.getByLabelText(/name/i), 'Rock Fans')
      await user.click(screen.getByRole('button', { name: /^save$/i }))
      await waitFor(() => expect(mockUpdate).toHaveBeenCalledOnce())
      expect(mockUpdate).toHaveBeenCalledWith(
        expect.objectContaining({ segmentId: segment.segment_id, name: 'Rock Fans' }),
        expect.any(Object)
      )
    })

    it('submits with empty estimated_size as undefined', async () => {
      const user = userEvent.setup()
      renderModal()
      await user.clear(screen.getByLabelText(/estimated size/i))
      await user.click(screen.getByRole('button', { name: /^save$/i }))
      await waitFor(() => expect(mockUpdate).toHaveBeenCalledOnce())
      expect(mockUpdate).toHaveBeenCalledWith(
        expect.objectContaining({ estimatedSize: undefined }),
        expect.any(Object)
      )
    })
  })

  describe('close behaviour', () => {
    it('calls onClose when Cancel is clicked', () => {
      const { onClose } = renderModal()
      fireEvent.click(screen.getByRole('button', { name: /^cancel$/i }))
      expect(onClose).toHaveBeenCalledOnce()
    })

    it('calls onClose when dialog close button is clicked', () => {
      const { onClose } = renderModal()
      fireEvent.click(screen.getByRole('button', { name: /^close$/i }))
      expect(onClose).toHaveBeenCalledOnce()
    })

    it('resets form to original values when closed and reopened', async () => {
      const user = userEvent.setup()
      const { onClose, rerender } = renderModal()

      // Edit the name
      await user.clear(screen.getByLabelText(/name/i))
      await user.type(screen.getByLabelText(/name/i), 'Changed')

      // Cancel (triggers reset)
      fireEvent.click(screen.getByRole('button', { name: /^cancel$/i }))
      expect(onClose).toHaveBeenCalledOnce()

      // Reopen
      rerender(
        <SegmentEditModal
          segment={segment}
          showId={SHOW_ID}
          open={true}
          onClose={onClose}
        />
      )

      expect(screen.getByLabelText(/name/i)).toHaveValue('Gen Pop')
    })
  })
})
